# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa97debb97bf530bad2fcc532a9fea751769ddacb02c29a1b35c69582799a7e224257b73a86fdfa62cba8845be32fb4c5a2a37623144bb64d6ea674aaf944f3

test:
  secret_key_base: f6c0d0b1501c1eea7ef68b05a257425fe178c11318620d98d19e91af4b442cafdf6f85d54a5934a1091864d0f4e585abf88af760668f4df538d84eb4ada74d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
